alias orbit='cd $DROPBOX/matrix/orbit'
alias helix='cd $DROPBOX/matrix/helix'
alias packages='cd $DROPBOX/matrix/packages'
alias lg='lazygit'
alias gs='git status'
alias cpush='configpush'
alias cpull='configpull'
