alias orbit='cd $DROPBOX/matrix/orbit'
alias bindu='cd $XDG_CONFIG_HOME'
alias helix='cd $DROPBOX/matrix/helix'
alias lilac='cd $DROPBOX/matrix/lilac'
alias tessera='cd $DROPBOX/matrix/tessera'
alias packages='cd $DROPBOX/matrix/packages'
alias lg='lazygit'
alias gs='git status'
